language: java
jdk:
  - oraclejdk7
  - openjdk7
env:
  matrix:
    - API_VERSION=2.8
    - API_VERSION=2.8.1
    - API_VERSION=2.8.2
    - API_VERSION=2.8.3
    - API_VERSION=2.8.4
    - API_VERSION=2.8.5
    - API_VERSION=2.9-rc1

install: true

before_script: ./script/before_build.sh

script:
  - ./gradlew build -PapiVersion=$API_VERSION
  - ./script/build.sh $API_VERSION
