language: java
jdk:
  - oraclejdk7
  - openjdk7
env:
  matrix:
    - API_VERSION=2.8
    - API_VERSION=2.8.1
    - API_VERSION=2.8.2
    - API_VERSION=2.8.3
    - API_VERSION=2.8.4
    - API_VERSION=2.8.5
    - API_VERSION=2.9
    - API_VERSION=2.9.1
    - API_VERSION=2.9.3
    - API_VERSION=2.10

install: true

script: ./gradlew build -PapiVersion=$API_VERSION
